version: '3.7'

services:
  db:
    #container_name: "db"
    build:
      context: ./db
      dockerfile: Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret2secret"
      MYSQL_DATABASE: "ceremony"
      MYSQL_USER: "secret"
      MYSQL_PASSWORD: "secret2secret"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - default

  angular-service:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - default

networks:
  default:
volumes:
  mysql_data:
